# Generated by Django 4.2.3 on 2023-08-25 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grados', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_asignatura', models.CharField(max_length=45, verbose_name='Asignatura')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='DocenteAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_asignatura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Asignatura', to='asignaturas.asignatura', verbose_name='Asignatura')),
                ('id_docente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Asignatura', to='usuarios.docente', verbose_name='Asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='CursoAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_docenteAsignatura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DocenteAsignatura', to='asignaturas.docenteasignatura', verbose_name='Docente Asignatura')),
                ('id_matricula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Matricula', to='grados.matricula', verbose_name='Matricula')),
            ],
        ),
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Calificación')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('id_cursoAsignatura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CursoAsignatura', to='asignaturas.cursoasignatura', verbose_name='Curso asignatura')),
            ],
        ),
    ]
