# Generated by Django 4.2.3 on 2023-08-25 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50, verbose_name='nombre')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellido usuario')),
                ('direccion', models.CharField(max_length=45, verbose_name='Direccion usuario')),
                ('num_telefono', models.CharField(max_length=45, verbose_name='numero telefónico del usuario')),
                ('password', models.CharField(max_length=45, verbose_name='Password usuario')),
                ('tipoDocumento', models.CharField(choices=[('C.C', 'Cédula de Ciudadanía'), ('C.E', 'Cédula de Extranjería'), ('T.I', 'Tarjeta de Identidad'), ('Pasaporte', 'pasaporte')], default='C.C', max_length=45, verbose_name='Tipo\xa0de\xa0Documento')),
                ('num_documento', models.CharField(max_length=45, verbose_name='Numero documento del usuario')),
                ('correo', models.CharField(max_length=45, verbose_name='correo usuario')),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Estudiante', 'Estudiante'), ('Docente', 'Docente')], default='Administrador', max_length=13, verbose_name='Rol')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Titulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_titulo', models.CharField(max_length=45, verbose_name='Título del docente')),
                ('Docente_id_Docente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.docente', verbose_name='título del docente')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(help_text='MM/DD/AAAA', verbose_name='fecha nacimiento del estudiante')),
                ('factor_rh', models.CharField(max_length=20, verbose_name='Factor RH estudiante')),
                ('num_telefono', models.CharField(max_length=45, verbose_name='Numero de telfono del estudiante')),
                ('nom_acudiente', models.CharField(max_length=50, verbose_name='nombre acudiente de estudiante')),
                ('telefono_acudiente', models.CharField(max_length=45, verbose_name='Numero de telefono del acudiente')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('Usuario_id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario', to='usuarios.usuario', verbose_name='Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='docente',
            name='Usuario_id_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='usuarios.usuario', verbose_name='usuario'),
        ),
    ]
