# Generated by Django 4.2.3 on 2023-08-25 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=20, verbose_name='Curso')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_grado', models.CharField(max_length=2, verbose_name='Grado')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='DD/MM/AAAA', verbose_name='fecha de Matricula')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('Estudiante_id_estudiante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Grado', to='usuarios.estudiante', verbose_name='Grado')),
                ('curso_id_curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Grado', to='grados.curso', verbose_name='Grado')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='Grado_id_grado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Grado', to='grados.grado', verbose_name='Grado'),
        ),
    ]
